### ISSUE TITLE
Calling channel.getMessages results to an Null Exception error. I think this is related to null promise being passed to that method.

### ISSUE THREAD

**Issue by Kabangi** [ccm-innovation/react-native-twilio-chat#12]
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.twilio.chat.Messages.getLastMessages(int, com.twilio.chat.CallbackListener)' on a null object reference
       at com.bradbumbalough.RCTTwilioChat.RCTTwilioChatMessages$5.onSuccess(RCTTwilioChatMessages.java:142)
       at com.bradbumbalough.RCTTwilioChat.RCTTwilioChatMessages$5.onSuccess(RCTTwilioChatMessages.java:134)
       at com.bradbumbalough.RCTTwilioChat.RCTTwilioChatMessages$1.onSuccess(RCTTwilioChatMessages.java:36)
       at com.bradbumbalough.RCTTwilioChat.RCTTwilioChatMessages$1.onSuccess(RCTTwilioChatMessages.java:33)
       at com.twilio.chat.internal.CallbackListenerForwarder$1.run(CallbackListenerForwarder.java:51)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by Kabangi** [comment]
I was able to make my code work by wrapping the calls to a setTimeout like this:- 

       
    this.twilioClient.onClientSynchronized = () => {
            setTimeout(() => {
                //Register Push tokens to receive Push notifications.
                if(this.user.device_tokens && this.user.device_tokens.length > 0){
                    this.user.device_tokens.forEach((token) => {
                       this.twilioClient.register(token);
                   })
               }

          this.twilioClient.getUserChannels().then(async (channels) => {
            channels = channels.items;
            if(channels.length > 0){
              this.totalChannels = channels.length;
              await this.saveChannelsLocally(channels);
              channels.forEach(ch => this.setupChannel(ch));
            }else{
              //TODO. Delete all existings conversations and their messages
              //that are synchronised since they seem not to exist on twilio any more.
              //Alternatively recreate them again.
              this.initialized$.onNext(true);
            }
          });
        },10);
      }
