### ISSUE TITLE
Channel getMessagesCount causes app to crash

### ISSUE THREAD

**Issue by simonasdev** [ccm-innovation/react-native-twilio-chat#37]
Hello,
In `onSuccess` calback for `getMessagesCount` method in `RCTTwilioChatChannels.java`, `Long` argument is being passed to `promise.resolve`, which, as far as I know, can't be done because react native doesn't implement conversion from Java `Long` to Javascript `Number`. The backtrace for the exception is as follows:
```java
FATAL EXCEPTION: mqt_native_modules
Process: com.medcall, PID: 8210
java.lang.RuntimeException: Cannot convert argument of type class java.lang.Long
   at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:57)
   at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:36)
   at com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:32)
   at com.bradbumbalough.RCTTwilioChat.RCTTwilioChatChannels$16$1.onSuccess(RCTTwilioChatChannels.java:505)
   at com.bradbumbalough.RCTTwilioChat.RCTTwilioChatChannels$16$1.onSuccess(RCTTwilioChatChannels.java:495)
   at com.twilio.chat.internal.CallbackListenerForwarder$1.run(CallbackListenerForwarder.java:31)
   at android.os.Handler.handleCallback(Handler.java:751)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:154)
   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
   at java.lang.Thread.run(Thread.java:761)
```
I've found, that it is suggested to use either 64bit double, or 53bit int (source: https://github.com/facebook/react-native/issues/9685)
Can anyone give suggestion how it should be implemented?

**Comment by simonasdev** [comment]
If anyone is looking for a quick hack to get the messages count, you can fetch the latest message with `getMessages(1)` and use the `index` property and increment it by 1. Note that this will probably only work if there are no deleted messages.
